---
- name: Wait for Kafka scheduler 
  become: yes
  run_once: true
  wait_for: 
    host: "{{ ansible_hostname }}"
    port: 7000 
    delay: 30
  tags:
    - kafka

- name: Add Kafka brockers  
  run_once: true
  become: yes
  command: "./kafka-mesos.sh broker add 0..{{ kafka_brokers - 1 }} --heap {{ kafka_broker_heap }} --mem {{ kafka_broker_memory }} --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_mesos_install_dir }}"
  tags:
    - kafka

- name: Start Kafka brockers  
  run_once: true
  become: yes
  command: "./kafka-mesos.sh broker start 0..{{ kafka_brokers - 1 }} --api http://{{ ansible_hostname }}:7000"
  args:
    chdir: "{{ kafka_mesos_install_dir }}"
  tags:
    - kafka
