---
- name: create logstash-server configuration directory
  become: yes
  file:
    path: /etc/logstash-server.d
    state: directory
    mode: 0755
  tags:
    - logstash-server

- name: configure logstash-server
  become: yes
  template:
    src: logstash.conf.j2
    dest: /etc/logstash-server.d/logstash.conf
  notify:
    - restart logstash-server
  tags:
    - logstash-server

- name: ensure logstash-server docker image is present
  become: yes
  command: /usr/bin/docker pull {{ logstash_image }}:{{ logstash_image_tag }}
  tags:
    - logstash-server
    - bootstrap

- name: generate logstash-server systemd service file
  become: yes
  template:
    src: logstash-service.j2
    dest: /usr/lib/systemd/system/logstash-server.service
  notify:
    - reload systemd daemon
    - enable and start logstash-server
  tags:
    - logstash-server

#- name: check if logstash-server syslog port is authorized
#  become: yes
#  shell: semanage port --list | grep "^syslogd_port_t.*tcp.*1514"
#  register: selinux_syslog_port_check
#  failed_when: no
#  changed_when: no
#  when: ansible_selinux.status == "enabled" and ansible_selinux.mode == "enforcing"
#  tags:
#    - logstash-server
#
#- name: authorize logstash-server syslog port
#  become: yes
#  shell: semanage port -a -t syslogd_port_t -p tcp 1514
#  when: selinux_syslog_port_check.rc is defined and selinux_syslog_port_check.rc != 0
#  tags:
#    - logstash-server

#- name: forward all logs from rsyslog to logstash
#  become: yes
#  lineinfile:
#    dest: /etc/rsyslog.conf
#    line: '*.* @@localhost:1514'
#  notify:
#    - restart rsyslog
#  tags:
#    - logstash

- meta: flush_handlers

- include: distributive.yml

- name: enasure logstash-server
  become: yes
  service:
    name: logstash-server
    state: started
  tags:
    - logstash-server